-- ==========================================
-- 1. FIX COUPONS TABLE AND POLICIES
-- ==========================================
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    description TEXT,
    discount_type TEXT NOT NULL DEFAULT 'PERCENTAGE',
    discount_value NUMERIC NOT NULL,
    min_order_value NUMERIC,
    expiration_date TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public access to active coupons" ON public.coupons;
DROP POLICY IF EXISTS "Users can manage coupons of their restaurants" ON public.coupons;
DROP POLICY IF EXISTS "Restaurant owners can manage coupons" ON public.coupons;
DROP POLICY IF EXISTS "Restaurant owners and admins can manage coupons" ON public.coupons;
DROP POLICY IF EXISTS "Anyone can read coupons" ON public.coupons;

CREATE POLICY "Anyone can read coupons" ON public.coupons
FOR SELECT USING (true);

CREATE POLICY "Restaurant owners and admins can manage coupons" ON public.coupons
FOR ALL USING (
  restaurant_id IN (
    SELECT id FROM public.restaurants WHERE owner_id = auth.uid()
  )
  OR
  (auth.jwt()->>'email' IN ('admin@guarafood.com.br', 'digitalpersonal@gmail.com'))
) WITH CHECK (
  restaurant_id IN (
    SELECT id FROM public.restaurants WHERE owner_id = auth.uid()
  )
  OR
  (auth.jwt()->>'email' IN ('admin@guarafood.com.br', 'digitalpersonal@gmail.com'))
);

-- ==========================================
-- 2. FIX PROMOTIONS TABLE AND POLICIES
-- ==========================================
CREATE TABLE IF NOT EXISTS public.promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    discount_type TEXT NOT NULL DEFAULT 'PERCENTAGE',
    discount_value NUMERIC NOT NULL,
    item_ids BIGINT[] DEFAULT '{}',
    combo_ids BIGINT[] DEFAULT '{}',
    category_ids BIGINT[] DEFAULT '{}',
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read promotions" ON public.promotions;
DROP POLICY IF EXISTS "Restaurant owners can manage promotions" ON public.promotions;
DROP POLICY IF EXISTS "Restaurant owners and admins can manage promotions" ON public.promotions;

CREATE POLICY "Anyone can read promotions" ON public.promotions
FOR SELECT USING (true);

CREATE POLICY "Restaurant owners and admins can manage promotions" ON public.promotions
FOR ALL USING (
  restaurant_id IN (
    SELECT id FROM public.restaurants WHERE owner_id = auth.uid()
  )
  OR
  (auth.jwt()->>'email' IN ('admin@guarafood.com.br', 'digitalpersonal@gmail.com'))
) WITH CHECK (
  restaurant_id IN (
    SELECT id FROM public.restaurants WHERE owner_id = auth.uid()
  )
  OR
  (auth.jwt()->>'email' IN ('admin@guarafood.com.br', 'digitalpersonal@gmail.com'))
);

-- ==========================================
-- 3. FIX EXPENSES TABLE AND POLICIES
-- ==========================================
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    date DATE NOT NULL,
    category TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Restaurant owners can read expenses" ON public.expenses;
DROP POLICY IF EXISTS "Restaurant owners can manage expenses" ON public.expenses;
DROP POLICY IF EXISTS "Restaurant owners and admins can manage expenses" ON public.expenses;

CREATE POLICY "Restaurant owners and admins can manage expenses" ON public.expenses
FOR ALL USING (
  restaurant_id IN (
    SELECT id FROM public.restaurants WHERE owner_id = auth.uid()
  )
  OR
  (auth.jwt()->>'email' IN ('admin@guarafood.com.br', 'digitalpersonal@gmail.com'))
) WITH CHECK (
  restaurant_id IN (
    SELECT id FROM public.restaurants WHERE owner_id = auth.uid()
  )
  OR
  (auth.jwt()->>'email' IN ('admin@guarafood.com.br', 'digitalpersonal@gmail.com'))
);
